<nav class="navbar is-warning" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="/">
            <img src="/gavel.png">
            <span style="font-size: 1.4rem; margin-left: 10px;">QuickLot</span>
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item" href="/">
                Home
            </a>

            <a class="navbar-item" href="/auctions">
                Auctions
            </a>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                    More
                </a>

                <div class="navbar-dropdown">
                    <a class="navbar-item">
                        About
                    </a>
                    <a class="navbar-item">
                        Contact
                    </a>
                    <hr class="navbar-divider">
                    <a class="navbar-item">
                        Report an issue
                    </a>
                </div>
            </div>
        </div>

        <div class="navbar-end">
            <div class="navbar-item">
                <?php use app\bframe\auth\Auth;

                if (Auth::loggedIn()) : ?>
                    <a href="/profile"><?= Auth::User()->name ?></a>

                    <form action="/logout" method="post">
                        <button type="submit" name="logout" class="button is-danger is-light ml-3">Logout</button>
                    </form>
                <?php else : ?>
                    <div class="buttons">
                        <a class="button is-danger" href="/signup">
                            <strong>Sign up</strong>
                        </a>
                        <a class="button is-light" href="/login">
                            Log in
                        </a>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</nav>