<?php


namespace app\bframe\relationships;


use app\bframe\facades\QB;

class HasOne extends Relationship
{
    public function get()
    {
        // DB QUERY TO GET
        if (is_null($this->result)) {

            $localKeyName = $this->localeKey ?? 'id';

            $data = QB::query()
                    ->select()
                    ->where($this->foreignKey, '=', $this->model->$localKeyName)
                    ->table($this->tableName)
                    ->model($this->className)
                    ->fetch();
            if ($data) {
                $this->result = $data;
            } else {
                $this->result = null;
            }
        }
        return $this->result;
    }

    public function create($dataArr, $return = false)
    {
        // If the hasOne already has a relationship then bail
        $found = QB::query()
            ->select()
            ->table($this->tableName)
            ->where($this->foreignKey, '=', $this->model->id)
            ->fetch();

        if ($found) {
            // Throw an error? Don't create it?
            throw new \Exception('Trying to add another relationship');
        } else {
            // Do the normal create
            return parent::create($dataArr, $return); // TODO: Change the autogenerated stub
        }

    }

}